### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of undefined in template function

### ISSUE THREAD

**Issue by Natdanai-Wongtib** [running-coder/jquery-typeahead#251] opened 2016-10-28 14:20 UTC
Hi everyone !!

I have a created typeahead template with the following configuration. but I can't access property in the item object. it error "**Uncaught TypeError: Cannot read property 'value' of undefined**" how I can I do it?

My template.
```javascript
template: function (query, item) {
    var template =  '<span class="thumbnail"><img src="{{thumbnail}}"></span>' +
			      '<span class="detail">' +
			      '<span class="date">{{date}}</span>'+	            
			      '<span class="title">{{title}}</span>' +
			      '<span class="meta">({{instructor}})</span>' +
			      '</span>'
      if (item.date) {
	       template += '<span class="ribbon">Top Rated</span>';
      }
      return template;
},
```
In configuration above i have access to **item.date** but not work. If i **console.log(item)** it output object data in the console. Like this.

![Image of Yaktocat](http://i.imgur.com/sJxW0A7.png)

**Comment by running-coder** [comment] 2016-10-28 15:58
Hey @Natdanai-Wongtib , your template seems right, would it be possible to use the unminified file and give me the line number of the error?

**Comment by Natdanai-Wongtib** [comment] 2016-10-28 16:36
Hi @running-coder currently i'm switch to unminified version but problem still exists.

![Image of Yaktocat](http://i.imgur.com/0V6vcdC.png)

Thank you.

**Comment by running-coder** [comment] 2016-10-28 16:58
hmm the error does not come from Typeahead, looks like it's from your own code?

**Comment by Natdanai-Wongtib** [comment] 2016-10-28 17:05
Yeah, This my full code. Everything seems to be working fine but item object in the template function doesn't work .

```javascript
        var $terms = phpvars.terms;

		var arr = [];
		var len = $terms.length;
		for (var i = 0; i < len; i++) {
		    arr.push({
		        key: 'terms',
			    value: $terms[i],
			    template: '{{terms}}',
			    all: "All Activity",
		    });
		}

		$.typeahead({
		    input: '.activity_search',
		    minLength: 0,
            maxItem: 6,
            maxItemPerGroup: 4,
            order: "desc",
            cache: false,
            dynamic: false,
            searchOnFocus: true,
            cancelButton: false,
            backdrop: {
		        "background-color": "#fff"
		    },
            group: {
                key: "terms",
            },
            groupOrder: phpvars.terms,
            emptyTemplate: 'No result for {{query}}',
            display: ["title"],
            dropdownFilter: arr,
            /*template: '<span class="thumbnail"><img src="{{thumbnail}}"></span>' +
	            '<span class="detail">' +
	            '<span class="date">{{date}}</span>'+	            
	            '<span class="title">{{title}}</span>' +
	            '<span class="meta">({{instructor}})</span>' +
	            '</span>',*/
	        template: function (query, item) {
			    var template =  '<span class="thumbnail"><img src="{{thumbnail}}"></span>' +
					            '<span class="detail">' +
					            '<span class="date">{{date}}</span>'+	            
					            '<span class="title">{{title}}</span>' +
					            '<span class="meta">({{instructor}})</span>' +
					            '</span>';

				console.log(item);
			    if (item.date) {
			        template += '<span class="ribbon">Top Rated</span>';
			    }
				return template;
			    
			},
	        correlativeTemplate: true,
            source: {
                terms: {
                	href: function (item) {
		                return item.link
		            },
                    ajax: function (query) {
		                return {
		                    type: 'POST',
		                    url: phpvars.ajaxurl,
		                    dataType: 'json',
		                    data: 'action=get_activity&name='+query,
		                }
		            }
                }
            }
        });
```

**Comment by running-coder** [comment] 2016-10-28 18:15
Hey, I was able to reproduce with your configurations. It was a special case with the combination of options you are using. Should be fixed now. Thanks for raising the issue!

**Closed** 2016-10-29 03:00 UTC
Labels: Bug
