### ISSUE TITLE
Is there / should there be an implicit order to search results?

### ISSUE THREAD

**Issue by sdillinger** [running-coder/jquery-typeahead#106] opened 2015-11-06 19:09 UTC
When I search for this string:  MW

I get these results:

![image](https://cloud.githubusercontent.com/assets/2574161/11005832/ce2ea576-8485-11e5-98e2-11aa65428828.png)

I feel the hint should be the second item, as it is a better match (at least the way I look at things).

As another example if I searched for  AP  against diaper and apple I would want the hint to be apple.

I guess this is an enhancement request.

Thanks!

**Comment by running-coder** [comment] 2015-11-10 05:34
it seems that the issue is with the correlativeTemplate option enabled because I've indeed set the hint as suggested.

**Comment by running-coder** [comment] 2015-11-10 05:36
can you paste your init code to be sure?

**Comment by running-coder** [comment] 2016-01-06 23:06
closing due to no reply

**Closed by running-coder** 2016-01-06 23:06 UTC
Labels: Bug, Cannot reproduce, Need more Information

**Comment by sdillinger** [comment] 2016-01-06 23:12
Apologies for not following up with this.  I'm not sure what the root issue was, I just remember I fixed it.  All things considered it was probably some problem on my side...

**Comment by running-coder** [comment] 2016-01-06 23:28
ah ok np thanks for letting me know
