### ISSUE TITLE
ng-click doesn't work anymore in version 2.6.1

### ISSUE THREAD

**Issue by GDM70** [running-coder/jquery-typeahead#197] opened 2016-05-09 10:25 UTC
Hello,

ng-click doesn't work anymore in version 2.6.1.
it worked flawlessly in version 2.3.4.

my code 

```
<div class="typeahead__container pull-left">
            <div class="typeahead__field">
                <span class="typeahead__query">
                    <input autocomplete="off"
                           id="input_l01a"
                           ng-model="p01c.klantid"
                           ng-click="p01c.clear()"
                           placeholder="typ hier uw zoekterm (min. 3 letters)" 
                           style="width:290px"
                           type="search">
                </span>
            </div>
         </div>
```

**Comment by running-coder** [comment] 2016-05-10 17:33
thanks for reporting I'll take a look shortly

**Comment by GDM70** [comment] 2016-05-11 09:15
Hey,

I found out that if I set cancelButton: false -> ng-click works again

**Comment by running-coder** [comment] 2016-05-12 01:14
what kind of sorcery is this... the `cancelButton` option doesn't unbind anything..

**Comment by running-coder** [comment] 2016-07-27 15:27
hey @GDM70 were you able to pinpoint/resolve the issue? I would like to resolve this one with the upcoming 2.7.0 version

**Comment by GDM70** [comment] 2016-07-28 18:51
no, I set cancelButton:false and that resolved my issue for the time being ;-)
I haven't been working on this issue anymore.

**Comment by running-coder** [comment] 2016-07-28 18:58
k k, I'll try to reproduce on one of my angular project or close it. Thanks

**Comment by running-coder** [comment] 2016-08-02 02:52
I've added Typeahead inside an Angular project, the `ng-click="clear()"` gets called when the input is cleared. The issue might be related to a particular Angular version / other implementation bindings, was unable to reproduce.

**Closed** 2016-08-02 02:52 UTC
Labels: Bug, Cannot reproduce
