### ISSUE TITLE
Typehead input not captured upon submitting an input form

### ISSUE THREAD

**Issue by swamyuma** [running-coder/jquery-typeahead#137] opened 2016-01-11 19:11 UTC
I am making an ajax request to a database which then returns values in an input field using the typhead plugin.  This part works fine as shown in the demos. But, but when I submit the input form, all other values are correctly captured, except the field with typhead plugin fed input value.  This field alone is coming back as None!  I do see the value in this field when printer using `console.log`! Am I missing something simple?

**Comment by running-coder** [comment] 2016-01-12 16:39
are you using the onSubmit callback or the regular form submit? (also does your input has a name? newbie mistake but I've done it a couple times in the past)

``` javascript
callback: {
    onSubmit: function (node, form, item, event) {
        console.log('~~~~~~~~~')
        console.log(node)
        console.log(form)
        console.log(item)
        console.log(event)
        console.log('~~~~~~~~~')
    }
},
```

**Comment by swamyuma** [comment] 2016-01-14 13:48
I checked to see if the input has a name attribute and it does. I don't understand the difference between " onSubmit callback or the regular form submit". 

Here are some screenshots 

```html
<input id="id_row_0_0" name="search_items" placeholder="Catalogue" size="1000" type="search" class="form-control valid" data-toggle="tooltip" autocomplete="off" aria-invalid="false" style="border-color: green;">
```

Step1. Input form
![image](https://cloud.githubusercontent.com/assets/13587232/12325736/f6d320c8-ba91-11e5-9bfd-1807b91f3459.png)

Step2. With typehead search

![image](https://cloud.githubusercontent.com/assets/13587232/12325790/4967d64e-ba92-11e5-85bc-a936e60adde2.png)

Step3. Trying Submit and nothing happens
![image](https://cloud.githubusercontent.com/assets/13587232/12325805/60be9116-ba92-11e5-97ea-18268b4cd422.png)

Any help is appreciated :+1:

**Comment by running-coder** [comment] 2016-01-14 16:17
onSubmit allows you to receive the complete item and control the data you want to send for example the text corresponds to "34182-309#..." but you want to send the ID for that item instead, or send the form as an ajax request

``` javascript
callback: {
    onSubmit: function (node, form, item, event) {
        $.ajax('myurl', {
            data: {
                id: item.id
            }
        }).done(function (response) {
            console.log('response')
        })
    }
}
```

I've tested the regular form submit and everything sends as it should... perhaps the mistake is somewhere in the html?

http://www.runningcoder.org/vendor/runningcoder/jquery-typeahead/example/demo-hockey_v1.html

**Comment by swamyuma** [comment] 2016-01-14 18:35
Thanks for the quick response, this is basically the html file, the form fields are automatically generated by `django` templating

```html
% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
<link rel="stylesheet" type="text/css" href="/static/stylesheets/web_worksheets.css">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<!-- for datepicker -->
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/humanity/jquery-ui.css">
<link rel="stylesheet" href="/static/js/jquery-typeahead-2.2.1/dist/jquery.typeahead.min.css">
</head>

<body>
{% block content %}
<br>
<form class="form-inline" method="post" id="SuppliesForm" style="width:1000px" enctype="multipart/form-data">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <span class="typeahead-button">
    <button  id="SubmitForm" type="submit" class="btn btn-success" value="Save">Submit</button>
    </span>
</form>
{% endblock content %}

<!-- online installs of BS3 and JQ -->
<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.14.0/jquery.validate.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<script src="/static/js/jQuery-autoGrowInput-master/jquery.auto-grow-input.min.js"></script>
<script src="/static/js/jquery-validation-bootstrap-tooltip/jquery-validate.bootstrap-tooltip.flickerfix.min.js"></script>
<script src="/static/js/jquery-typeahead/src/jquery.typeahead.js"></script>

<script src="/static/js/supplies_input.js"></script>
</body>

</html>
```

And the `supplies_input.js`

```js
$().ready(function(){

  $('input').addClass('form-control');
  $('input').attr({'data-toggle':'tooltip'});

  $('#id_purchase_id_0').autoGrowInput({minWidth: 100, maxWidth: 800, comfortZone: 40});

  var rows = $('input[name$="_0"]')
  rows.splice(0,1)

  $('input[name="search_items"]').each(function(){
  //rows.each(function(){
    $(this).attr({name:"search_items", type:"search", autocomplete:"off"});
    $(this).wrap("<div class='typeahead-container'><div class='typeahead-field'><span class='typeahead-query'></span> </div> </div>")
  })

  $('input[placeholder="Description"]').each(function(){
    $(this).autoGrowInput({minWidth: 100, maxWidth: 800, comfortZone: 90});
  });

 var token = $('input[name="csrfmiddlewaretoken"]').prop('value');

  $('input[name="search_items"]').each(function(){
  //rows.each(function(){
    $.typeahead({
        input: $(this),
        order: "asc",
        hint: true,
        group: ["VendorName", "{{group}}"],
        display: ["ProductName", "VendorName", "ProductCatalog"],
        template: '<span>' +
            '<span class="ProductDescription">{{ProductCatalog}}</span>' +
            '<span class="CastNumber">#{{CastNumber}}</span>' +
            '<span class="VendorName">#{{VendorName}}</span>' +
            '<span class="ItemNumber">#{{ItemNumber}}</span>' +
            '<span class="ProductName">#{{ProductName}}</span>' +
            '</span>',
        correlativeTemplate: true,
        source: {
            catalog: {
                crossDomain: true,
                url: "check_supplies", //django view that returns a json object 
                type: "post",
                callback :{
                  done: function (data, textStatus, jqXHR) {
                    console.log(data);
                    alert(textStatus);
                    return data
                  },
                  complete: function (jqXHR, textStatus) {
                    $(this).autoGrowInput({minWidth: 100, maxWidth: 800, comfortZone: 90});
                    alert(textStatus)
                  },
                  fail: function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus)
                  },
                },
            },
        callback: {
//          onSubmit: function (node, form, item, event) {
//            console.log('~~~~~~~~~')
//            console.log(node)
//            console.log(form)
//            console.log(item)
//            console.log(event)
//            console.log('~~~~~~~~~')
//            },
            onClickAfter: function(node, a, item, event) {
              console.log(item.ProductCatalogue, item.ItemNumber);
            }
        }
      });//typhead
  });//for each loop
}); // outermost
```

**Comment by running-coder** [comment] 2016-01-14 19:21
at first I thought that the problem might be caused by the fact that your input names are all the same, but I see that the browser stack them up on submit 

![2016-01-14_1419](https://cloud.githubusercontent.com/assets/7377382/12334800/faf9d5c4-bac9-11e5-985b-0ec9c4a7ea45.png)

Perhaps your parser strips similar names? At this point I think it depends on the technology you are using and not Typeahead itself

**Comment by running-coder** [comment] 2016-01-14 19:25
Also, I'm surprised that your source is working... I've setted it following this pattern (extra ``url`` object inside ``catalog``)

``` javascript
catalog: {
    url: {
        type: "POST",
        url: "check_supplies",
        data: {
            myKey: "myValue",
        },
        crossDomain: true,
        beforeSend: function (jqXHR, options) {
            jqXHR.setRequestHeader('Authorization', 'Bearer xxxxxxxxxxxx');
        },
        callback: {
            done: function (data, textStatus, jqXHR) {
                console.log(data);
                alert(textStatus);
                return data
            },
            complete: function (jqXHR, textStatus) {
                $(this).autoGrowInput({minWidth: 100, maxWidth: 800, comfortZone: 90});
                alert(textStatus)
            },
            fail: function (jqXHR, textStatus, errorThrown) {
                alert(textStatus)
            }
        }
    }
}
```

**Comment by running-coder** [comment] 2016-01-23 04:54
closing due to no-reply

**Closed by running-coder** 2016-01-23 04:54 UTC
Labels: Support

**Comment by swamyuma** [comment] 2017-05-28 12:47
Apologize for reopening this issue. Can you please show a demo of multicolumn typehead example? After a year, I still can't get the multicolumn example above to submit.
