### ISSUE TITLE
Hide autocomplete suggestions when textinput loses focus.

### ISSUE THREAD

**Issue by nevara** [running-coder/jquery-typeahead#270] opened 2016-12-20 10:10 UTC
Hello,

I'm using this plugin for each column of my table. If I click into another textfield the autocomplete of the previous textfield is not hidden. It would be great to hide it.

**Comment by running-coder** [comment] 2016-12-22 17:17
hey @nevara, when Typeahead looses focus the search results are hidden... the behavior can be tested on the demo page: http://www.runningcoder.org/jquerytypeahead/demo/

**Comment by tombertrand** [comment] 2017-01-02 16:44
If you can provide a demo with the behaviour you are describing it would be great. Meanwhile I'll leave this one closed as cannot reproduce

**Comment by running-coder** [comment] 2017-01-02 16:45
If you can provide a demo with the behaviour you are describing it would be great. Meanwhile I'll leave this one closed as cannot reproduce

**Comment by nevara** [comment] 2017-01-03 09:12
Hi Tom,

Happy New Years!

I created a demo for you:

https://jsfiddle.net/7ubdb09s/

It’s missing your CSS, but the issue is shown.

Thanks for replying!

Viele Grüße

Pan Theis
Mobile +49 176 63211947

On 2 Jan 2017, at 17:45, Tom Bertrand <notifications@github.com<mailto:notifications@github.com>> wrote:


If you can provide a demo with the behaviour you are describing it would be great. Meanwhile I'll leave this one closed as cannot reproduce

**Comment by running-coder** [comment] 2017-01-03 16:26
Hey @nevara thanks, Happy new years also!

I've looked into the issue and it is due to 2 things, first if you look into your console and type "Typeahead", each init needs it's unique selector. Also the selector property was removed in jQuery3 https://api.jquery.com/selector/.

I've made a demo from yours that fixes the issue using "input" option and a unique selector per Typeahead init. I'll add a custom attribute in future release to bypass this "hack" but meanwhile you can use it like this: https://jsfiddle.net/runningcoder/peqgn4fa/

**Comment by nevara** [comment] 2017-01-03 17:13
Thanks! It works!
Only thing is, when clicking into a typeahead input, the datatable sorting mechanism is triggered. Before, I could stop it with        

$('input', this.header()).on('click', function (e) { // exclude input field from sorting trigger.
            e.stopPropagation();
        });

but with that code, the typeahead is not hidden, thus the original problem appears. 

It seems to be mainly an datatable issue, but I cannot find any solution disabling the sorting trigger for the datatable. (I still want sorting, but only when clicking the sorting arrows or in the header).

**Comment by running-coder** [comment] 2017-01-03 21:15
oh, perhaps you can try to catch the TH click when it's on the input (event.target.nodeName) and destroy the event + trigger a manual Typeahead focus `Typeahead[inputname].node.trigger('focus.typeahead')`. This might not work but worth a try... Unfortunately I do not support behaviour from other plugins when mixed with Typeahead, that would be too much work and exceptions..

**Comment by nevara** [comment] 2017-01-04 08:54
Thanks!

I solved it by turning the header into a footer.

**Comment by running-coder** [comment] 2017-01-04 16:09
cool, let me know if anything

**Comment by running-coder** [comment] 2017-01-04 16:10
Leaving this opened to fix the selector for jquery3

**Closed** 2017-01-18 00:40 UTC
Labels: Bug

**Comment by kavin-90** [comment] 2017-01-18 06:49
I use jquery 3 and have no problem with my old codes everything is superb.

I'm using @version 2.7.4 (2016-12-8)

**Comment by running-coder** [comment] 2017-01-18 12:39
The issue is caused by $(element).selector being removed in jquery3, this caused issues when multiple typeahead on 1 page from not closing themselves when focus out and since selector is used to create window.Typeahead[SELECTOR] it was given the name of undefined, you could only have 1 referenced in the window scope for manual manipulations
